apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-example
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-example
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-example
    spec:
      containers:
        - name: example
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
